export const RouterApi = {
  login: '/auth/login',
  createUser: '/user/create',
  updateUser: '/user/update',
  userAll: '/user/all',
  userPublic: '/user/public',
  findUser: '/user/find',
  changePasswordUser: '/user/changePassword',
  checkRole: '/user/checkRole',
  roleAll: '/role/all',
  cateConceptAll: '/category-concept/all',
  conceptAdd: '/concept/add',
  conceptUpdate: '/concept/update',
  conceptHistory: '/concept/history',
  conceptAll: '/concept/all',
  conceptDelete: '/concept/delete',
  conceptDetail: '/concept/detail',
  conceptAccept: '/concept/accept',
  conceptDownload: '/concept/download',
  conceptDownloadMultiple: '/concept/download-multiple',
};
