import { Chip } from "@mui/material";

export const LIST_COL_MOLD = [
    { canHide: false, align: 'center', name: '#', id: '#', width: 20 },
    { canHide: false, align: 'center', name: 'Category', id: 'category', width: 100 },
    { canHide: false, align: 'center', name: 'Project', id: 'project', width: 100 },
    { canHide: false, align: 'center', name: ' 구분', id: 'type', width: 100 },
    { canHide: false, align: 'center', name: 'Model', id: 'model', width: 100 },
    { canHide: true, align: 'center', name: 'Description', id: 'description', width: 150 },
    { canHide: false, align: 'center', name: 'Mold No.', id: 'moldNo', width: 100 },
    { canHide: true, align: 'center', name: '제작업체<br/>NSX', id: 'manufacturer', width: 100 },
    { canHide: true, align: 'center', name: '발송지역<br/>Nơi VC', id: 'shipArea', width: 120 },
    { canHide: true, align: 'center', name: '출고 계획<br/>Thời gian', id: 'shipDate', width: 100 },
    { canHide: false, align: 'center', name: '양산업체<br/>Cty SX', id: 'massCompany', width: 100 },
    { canHide: false, align: 'center', name: '양산업체입고<br/>Thời gian', id: 'shipMassCompany', width: 110 },
    { canHide: false, align: 'center', name: '수정업체<br/>Nơi sửa', id: 'modificationCompany', width: 100 },
    { canHide: false, align: 'center', name: '수리 출고<br/>Xuất kho sửa', id: 'outputEdit', width: 100 },
    { canHide: false, align: 'center', name: '입고 계획<br/>Xuất tới', id: 'wearingPlan', width: 100 },
    { canHide: false, align: 'center', name: '입고 완료<br/>Thời gian', id: 'receivingCompleted', width: 100 },
    { canHide: true, align: 'center', name: 'TRY NO.', id: 'tryNo', width: 100 },
    { canHide: true, align: 'center', name: '수정내역<br/>Nội dung sửa', id: 'historyEdit', width: 120 },
    { canHide: false, align: 'center', name: '양산적용<br/>Trạng thái', id: 'productionStatus', width: 100 },

];
export const LIST_STATUS = [
    { id: 'DEV', name: '개발중(Đang phát triển)', value: 'DEV' },
    { id: 'USE', name: '양산(Đang sản xuất)', value: 'USE' },
    { id: 'STOP', name: '사용중지(Ngừng sử dụng)', value: 'STOP' },

];



// 개발중(dev) / 양산(use) / 사용중지(stop)

export const FAKE_DATA = [
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#003', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/04/01', massCompany: 'SEOWON', shipMassCompany: '24/04/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'USE', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#011', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/24', massCompany: 'SEOWON', shipMassCompany: '24/05/24', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#012', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/25', massCompany: 'SEOWON', shipMassCompany: '24/05/25', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#013', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/04/26', massCompany: 'SEOWON', shipMassCompany: '24/04/26', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#014', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'SEOWON', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#015', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/22', massCompany: 'SEOWON', shipMassCompany: '24/05/22', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#016', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/25', massCompany: 'SEOWON', shipMassCompany: '24/05/25', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND L', model: 'SM-L315U', description: 'STRAP WAVE HOLE LARGE V2', moldNo: '#017', manufacturer: 'GUNPO', shipArea: 'GUNPO', shipDate: '24/05/27', massCompany: 'SEOWON', shipMassCompany: '24/05/27', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V1', moldNo: '#003', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/04/01', massCompany: 'SEOWON', shipMassCompany: '24/04/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#003', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/04/01', massCompany: 'SEOWON', shipMassCompany: '24/04/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#018', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/04/26', massCompany: 'SEOWON', shipMassCompany: '24/04/26', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#019', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'SEOWON', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#020', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'BINH KIEN', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#021', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/05/30', massCompany: 'SEOWON', shipMassCompany: '24/05/30', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#022', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/05', massCompany: 'SEOWON', shipMassCompany: '24/06/05', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#023', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'SEOWON', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#024', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/03', massCompany: 'SEOWON', shipMassCompany: '24/06/03', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#025', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/05/21', massCompany: 'SEOWON', shipMassCompany: '24/05/21', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#026', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/07', massCompany: 'SEOWON', shipMassCompany: '24/06/07', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#027', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/07', massCompany: 'SEOWON', shipMassCompany: '24/06/07', modificationCompany: 'SEOWON' },
    { productionStatus: 'USE', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#028', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/03', massCompany: 'SEOWON', shipMassCompany: '24/06/03', modificationCompany: 'SEOWON' },
    { productionStatus: 'USE', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#029', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/07', massCompany: 'SEOWON', shipMassCompany: '24/06/07', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BAND S', model: 'SM-L305U', description: 'STRAP_WAVE HOLE SMALL V2', moldNo: '#030', manufacturer: 'JEONJIN', shipArea: 'GUNPO', shipDate: '24/06/01', massCompany: 'SEOWON', shipMassCompany: '24/06/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'USE', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V1', moldNo: '#003', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/01', massCompany: 'SEOWON', shipMassCompany: '24/04/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'DEV', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#003', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/01', massCompany: 'BINH KIEN', shipMassCompany: '24/04/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#025', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/22', massCompany: 'SEOWON', shipMassCompany: '24/04/22', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#026', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/24', massCompany: 'SEOWON', shipMassCompany: '24/04/24', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#027', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/26', massCompany: 'SEOWON', shipMassCompany: '24/04/26', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#028', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/09', massCompany: 'SEOWON', shipMassCompany: '24/05/09', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#029', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/04/29', massCompany: 'SEOWON', shipMassCompany: '24/04/29', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#030', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/27', massCompany: 'SEOWON', shipMassCompany: '24/05/27', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#031', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'SEOWON', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#032', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/04', massCompany: 'SEOWON', shipMassCompany: '24/05/04', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#033', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/09', massCompany: 'SEOWON', shipMassCompany: '24/05/09', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#034', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/09', massCompany: 'SEOWON', shipMassCompany: '24/05/09', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#035', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/10', massCompany: 'SEOWON', shipMassCompany: '24/05/10', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#036', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/10', massCompany: 'SEOWON', shipMassCompany: '24/05/10', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#037', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/23', massCompany: 'SEOWON', shipMassCompany: '24/05/23', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#038', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/23', massCompany: 'SEOWON', shipMassCompany: '24/05/23', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#039', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/29', massCompany: 'SEOWON', shipMassCompany: '24/05/29', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#040', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/24', massCompany: 'SEOWON', shipMassCompany: '24/05/24', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#041', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/29', massCompany: 'SEOWON', shipMassCompany: '24/05/29', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#042', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/06/01', massCompany: 'SEOWON', shipMassCompany: '24/06/01', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#043', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/30', massCompany: 'SEOWON', shipMassCompany: '24/05/30', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#044', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/29', massCompany: 'SEOWON', shipMassCompany: '24/05/29', modificationCompany: 'SEOWON' },
    { productionStatus: 'STOP', tryNo: 'T0', category: 'RUBBER', project: 'WATCH7', type: 'BUCKLE', model: 'SM-L305U', description: 'STRAP_WAVE BUCKLE V2', moldNo: '#045', manufacturer: 'SEONJAE', shipArea: 'GUNPO', shipDate: '24/05/30', massCompany: 'SEOWON', shipMassCompany: '24/05/30', modificationCompany: 'SEOWON' },

]